# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/OExp02-IP2SOC/A7.xdc

# IP: ip/RAM_B/RAM_B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_B || ORIG_REF_NAME==RAM_B} -quiet] -quiet

# IP: ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# XDC: k:/Computer_organization/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/RAM_B/RAM_B_ooc.xdc

# XDC: k:/Computer_organization/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
