# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: k:/Computer_organization/OExp02-IP2SOC/OExp02-IP2SOC.srcs/sources_1/ip/ROMForCSR/ROMForCSR.xci
# IP: The module: 'ROMForCSR' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: k:/Computer_organization/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/ROMForCSR/ROMForCSR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROMForCSR'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: k:/Computer_organization/OExp02-IP2SOC/OExp02-IP2SOC.srcs/sources_1/ip/ROMForCSR/ROMForCSR.xci
# IP: The module: 'ROMForCSR' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: k:/Computer_organization/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/ROMForCSR/ROMForCSR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROMForCSR'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
